name: "Build & test App"

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: shivammathur/setup-php@v2
        with:
          php-version: "8.4"
          extensions: sqlite, mbstring, bcmath, pdo

      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"

      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: Generate key
        run: php artisan key:generate

      - name: Create Databases
        run: |
          mkdir -p database
          touch database/database.sqlite
          touch database/testing.sqlite

      - name: Prepare test database (migrate + seed)
        env:
          DB_CONNECTION: sqlite
          DB_DATABASE: database/testing.sqlite
        run: php artisan migrate:fresh --seed --no-interaction

      - name: Execute tests
        env:
          DB_CONNECTION: sqlite
          DB_DATABASE: database/testing.sqlite
          FAST_DB_SKIP_MIGRATE: "true"
        run: php artisan test

